name: Run application's tests on github virtual machine
on: push
jobs:
  app_testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - run: python3 -m venv .venv
    - run: source .venv/bin/activate
    - name: Install dependencies
      run: pip install --no-cache-dir -r requirements.txt
    - name: Run application's tests
      run: python -m pytest
