name: Run application's tests and lint on github virtual machine
on: push
jobs:
  app_testing_and_linting:
    runs-on: self-hosted
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ./.venv/
          key: ${{ runner.os }}-python-packages-${{ hashFiles('./requirements_dev.txt') }}
      - name: Install python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Make environment
        run: python3 -m venv .venv
      - name: Activate environment
        run: source .venv/bin/activate
      - name: Check path to environment
        run: pip -V
      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements_dev.txt
      - name: Run application's tests
        run: python -m pytest
      - name: Lint application
        run: pylint .
