name: Build and run app with docker compose
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: List source folder
        run: |
          pwd
          ls -la ..
      - name: Move all app files to build dir
        run: mv ../${{ github.event.repository.name }} /opt/app
      - name: List destination folder
        working-directory: /opt/app
        run: |
          pwd
          ls -la ..
      - name: Run docker compose up
        working-directory: /opt/app
        run: docker compose up --build -d

